server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/voucher-service
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    hibernate:
      ddl-auto: create
application:
  third-party:
    host: http://host.docker.internal:8081
    api:
      ping: ${application.third-party.host}/ping
      voucher: ${application.third-party.host}/voucher